searchhaus:
  appName: app-default
  licenseFile: yourlicense.file
  repositoryDirectory: ../repository
  relevanceAssessmentDirectory: ../benchmarks/relevance_assessments

  doWarmup: true
  enableSparqlEndpoint: true

  repositoryDataStore:
    type: sparql
    managed: false
    mode: quads
    internalKeyValidation: false
    remoteEndpoint: http://blazegraph:8080/blazegraph/sparql
    localEndpoint: http://graphscope:9090/graphscope/api/sparql
    disableBlazegraphOptimizer: "true"


  dataSearch:
    analysis: translation-index-analysis-english.json
    showSPARQL: true
    showValuesOfAttributeValueMatches: true
    highlightAttributeValueMatches: true
    enableMultiConceptQueries: true

    priors:
      ## blazegraph only, use frequency without -bg suffix otherwise
      #- type: frequency-bg
      #  predicates: true
      ## blazegraph only, use pagerank without -bg suffix otherwise
      - type: pagerank-bg
      - type: configuration
        predicateWeights:
          http://www.w3.org/2004/02/skos/core#prefLabel: 2.0
          http://www.w3.org/2000/01/rdf-schema#label : 2.0
          http://xmlns.com/foaf/0.1/name : 1.5
          http://purl.org/dc/terms/title : 1.5
          http://www.w3.org/2004/02/skos/core#altLabel: 1.1

    queryTranslation:
      timeLimit: 5000
      validityCheckTimeLimit: 5000
      enableDirectSubgraphGeneration: false
      maxSubgraphSize: 4
      maxTranslations: 1
      alternativeMatchesFromTranslations: false
      subgraphLimit: 5

      matching:
        conceptMatchWeight: 1.0
        relationMatchWeight: 0.8
        attributeMatchWeight: 0.8
        attributeValueMatchWeight: 1
        multipleKeywordsWeight: 1.8

        segmentation:
          enabled: true
          threshold: 1.0

      scoring:
        type: graphscoring

      matchScoring:
        type: graphelement

      suggest:
        termFrequencyThreshold: 1

      consolidation:
        steps:
          - segmentedAggregateByTopScoreClassHierarchy
          - pruneTG
          - limitMatchCounts
          - idNodes
          - reflexsiveTGEdges
          - generateMatchedConcepts

    resultTable:
      countAll: false
      autoSort: false

  dataSet:
    labelLanguages: ['en']
    labelPredicates:
      - http://www.w3.org/2004/02/skos/core#prefLabel
      - http://www.w3.org/2000/01/rdf-schema#label
      - http://xmlns.com/foaf/0.1/name
      - http://www.w3.org/2004/02/skos/core#altLabel

    replaceInEntityLinks:
      prefix: "/resource/?uri="

    ignoredPredicates:
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#type
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#first
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#rest
      - http://www.w3.org/2000/01/rdf-schema#domain
      - http://www.w3.org/2000/01/rdf-schema#range
      - http://www.w3.org/2000/01/rdf-schema#subPropertyOf
      - http://www.w3.org/2002/07/owl#disjointWith
      - http://www.w3.org/2002/07/owl#unionOf
      - http://www.w3.org/2002/07/owl#imports

    ignoredTypes:
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#Property
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#value
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#nil
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#List
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#first
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#rest
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#XmlLiteral
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#subject
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#object
      - http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement
      - http://www.w3.org/2000/01/rdf-schema#Class
      - http://www.w3.org/2000/01/rdf-schema#ContainerMembershipProperty
      - http://www.w3.org/2000/01/rdf-schema#Domain
      - http://www.w3.org/2000/01/rdf-schema#Range
      - http://www.w3.org/2000/01/rdf-schema#isDefinedBy
      - http://www.w3.org/2000/01/rdf-schema#Datatype
      - http://www.w3.org/2000/01/rdf-schema#Comment
      - http://www.w3.org/2000/01/rdf-schema#label
      - http://www.w3.org/2000/01/rdf-schema#Resource
      - http://www.w3.org/2000/01/rdf-schema#Container
      - http://www.w3.org/2000/01/rdf-schema#Literal
      - http://www.w3.org/2002/07/owl#Restriction
      - http://www.w3.org/2002/07/owl#FunctionalProperty
      - http://www.w3.org/2002/07/owl#AnnotationProperty
      - http://www.w3.org/2002/07/owl#InverseFunctionalProperty
      - http://www.w3.org/2002/07/owl#TransitiveProperty


#    concepts:
#          # Concepts are identified by their URI.
#        - concept: http://xmlns.com/foaf/0.1/Person
#          ignoredPredicates:
#            - http://xmlns.com/foaf/0.1/firstName
#            - http://xmlns.com/foaf/0.1/lastName

    facets:
      valueCount: 50
      order:
        - http://www.w3.org/2006/vcard/ns#org
        - http://www.w3.org/2006/vcard/ns#postal-code

      excluded:
        - http://www.w3.org/2000/01/rdf-schema#label
        - http://www.w3.org/1999/02/22-rdf-syntax-ns#type

      clustering:
        minValueCount: 7
        clusterCount: 4
        clustered:
          - http://www.w3.org/2006/vcard/ns#postal-code

  documentSearch:
    enabled: false

  security:
    # htpasswd file must use bcrypt (requires htpasswd tool from Apache 2.4 or use http://aspirine.org/htpasswd_en.html)
    htpasswdFile: users.htpasswd
    users:
      - name: admin
        roles:
          - ROLE_ADMIN
          - ROLE_USER
    #  - name: dataupdate
    #    roles:
    #      - ROLE_DATA_UPDATE
    #  - name: searcher
    #    roles:
    #      - ROLE_USER

server:
  type: simple
  applicationContextPath: /graphscope/
  adminContextPath: /graphscope/jetty-admin
  connector:
    type: http
    port: 9090
    bindHost: 0.0.0.0

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    net.searchhaus: INFO
    org.elasticsearch.de.spinscale: WARN
    org.elasticsearch: INFO

  appenders:
    - type: console
    - type: file
      currentLogFilename: ../logs/app.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: ../logs/app.%d.log.gz
      archivedFileCount: 31

    - type: elasticsearch
      indexNamePattern: "'logstash-'yyyy.MM"
