version: "2.2"
services:
  metaphactory:
    # metaphactory overwrites here
    ports:
      - "10214:8080"
    #  - "10213:8443"
    #mem_limit: 1g
    #mem_reservation: 1g
    #environment:
    #extra_hosts:
    #  - "hostmachine:172.17.0.1"
  #graphscope:
    # graphscope overwrites here
    #mem_limit: 2g
    #mem_reservation: 2g
    #environment:
    #  REMOTE_USER: admin
    #  REMOTE_PWD: mypasswd
