version: "2.2"
services:
  nginx-proxy:
    # uncomment to adjust nginx template configuration
    #environment:
    #  - "SSL_POLICY=Mozilla-Modern"
    #  - "REFERRER_POLICY=off"

networks:
  proxy_network:
# uncomment the two lines below if you run docker-compose for nginx after other containers have already connected to the network
#    name: nginx_proxy_network
#    external: true
