version: "2.2"
services:
 metaphactory-data:
  container_name: "${COMPOSE_PROJECT_NAME}-metaphactory-data"
  image: "${METAPHACTORY_DATA_IMAGE}"

 metaphactory:
  container_name: "${COMPOSE_PROJECT_NAME}-metaphactory"
  image: "${METAPHACTORY_IMAGE}"
  restart: unless-stopped
  environment:
     - PLATFORM_OPTS=${METAPHACTORY_OPTS}
     - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}.${HOST_NAME}
     - JAVA_OPTS=-Xmx1g
     - GENERATE_METAPHACTORY_PASSWORD=${GENERATE_METAPHACTORY_PASSWORD}
     # LETSENCRYPT variables will take effect only when nginx-proxy is setup with Let's Encrypt support
     - LETSENCRYPT_HOST=${COMPOSE_PROJECT_NAME}.${HOST_NAME}
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  volumes_from:
     - metaphactory-data
  networks:
     - default
     - metaphactory_network
  depends_on:
       - metaphactory-data
  logging:
   driver: json-file
   options:
    max-size: "200k"
    max-file: "10"

networks:
  default:
    external:
      name: nginx_proxy_network
  metaphactory_network:
