version: "2.2"
services:

 metaphactory:
  container_name: "${COMPOSE_PROJECT_NAME}-metaphactory"
  image: "${METAPHACTORY_IMAGE}"
  restart: unless-stopped
  mem_limit: 1g
  mem_reservation: 1g
  environment:
     - PLATFORM_OPTS=${METAPHACTORY_OPTS}
     - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}.${HOST_NAME}
     - JAVA_OPTS=
     - GENERATE_METAPHACTORY_PASSWORD=${GENERATE_METAPHACTORY_PASSWORD}
     # LETSENCRYPT variables will take effect only when nginx-proxy is setup with Let's Encrypt support
     - LETSENCRYPT_HOST=${COMPOSE_PROJECT_NAME}.${HOST_NAME}
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  networks:
#     - default
     - metaphactory_network
  volumes:
     - metaphactory-runtime-data:/runtime-data
     - metaphactory-apps:/apps
     - metaphactory-storage:/storage
  logging:
   driver: json-file
   options:
    max-size: "200k"
    max-file: "10"

volumes:
  metaphactory-runtime-data:
  metaphactory-apps:
  metaphactory-storage:

networks:
#  default:
#    external:
#      name: nginx_proxy_network
  metaphactory_network:
