version: "2.2"
services:

 metaphactory:
  container_name: "${COMPOSE_PROJECT_NAME}-metaphactory"
  image: "${METAPHACTORY_IMAGE}"
  restart: unless-stopped
  environment:
     - PLATFORM_OPTS=-Dlog4j.configurationFile=file:///var/lib/jetty/webapps/etc/log4j2-trace2.xml ${METAPHACTORY_OPTS}
     - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}.${HOST_NAME}
     - JAVA_OPTS=-Xmx1g
     - GENERATE_METAPHACTORY_PASSWORD=${GENERATE_METAPHACTORY_PASSWORD}
     # LETSENCRYPT variables will take effect only when nginx-proxy is setup with Let's Encrypt support
     - LETSENCRYPT_HOST=${COMPOSE_PROJECT_NAME}.${HOST_NAME}
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  networks:
     - default
     - metaphactory_network
  volumes:
     - metaphactory-runtime-data:/runtime-data
  logging:
   driver: json-file
   options:
    max-size: "200k"
    max-file: "10"

volumes:
  metaphactory-runtime-data:

networks:
  default:
    external:
      name: nginx_proxy_network
  metaphactory_network:
