version: "2.2"
services:
 blazegraph:
  container_name: "${COMPOSE_PROJECT_NAME}-blazegraph"
  image: "${BLAZEGRAPH_IMAGE}"
  restart: unless-stopped
  volumes:
     - blazegraph-data:/blazegraph-data
  environment:
     - JAVA_OPTS=-Xmx1g
  networks:
     - metaphactory_network
  logging:
   driver: json-file
   options:
    max-size: "200k"
    max-file: "10"

 metaphactory:
  environment:
     - PLATFORM_OPTS=-Dconfig.environment.sparqlEndpoint=http://${COMPOSE_PROJECT_NAME}-blazegraph:8080/blazegraph/sparql ${METAPHACTORY_OPTS}
  depends_on:
       - blazegraph


volumes:
  blazegraph-data:
